### ISSUE TITLE
Installation tests failed on Linux

### ISSUE THREAD

**Issue by nbdsp** [PadreIDE/Padre#13]
When installing from CPAN, two tests failed:

------ 1-st : --------
t/01_compile.t ............. 36/37 
 #   Failed test 'no warnings'
 #   at /home/al/perl5/lib/perl5/Test/NoWarnings.pm line 45.
 # There were 1 warning(s)
 # 	Previous test 26 'use Padre::Role::Task;'
 # 	Possible precedence issue with control flow operator at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre/Document/Perl/QuickFix/StrictWarnings.pm line 71.
 #  at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre/Document/Perl/QuickFix/StrictWarnings.pm line 71.
 # 	require Padre/Document/Perl/QuickFix/StrictWarnings.pm called at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre.pm line 87
 # 	eval {...} called at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre.pm line 87
 # 	Padre::import("Padre", ":everything") called at t/01_compile.t line 53
 # 
 # Looks like you failed 1 test of 37.

-------- 2-nd: -----------

t/50_browser.t ............. 1/14 
 #   Failed test 'undef isa 'Padre::Browser::Document''
 #   at t/50_browser.t line 47.
 #     undef isn't defined
Can't call method "mimetype" on an undefined value at t/50_browser.t line 48.
 # Looks like you planned 14 tests but ran 9.
 # Looks like you failed 1 test of 9 run.
 # Looks like your test exited with 25 just after 9.
t/50_browser.t ............. Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 6/14 subtests 

Test Summary Report
-------------------
t/01_compile.t           (Wstat: 256 Tests: 37 Failed: 1)
  Failed test:  37
  Non-zero exit status: 1
t/50_browser.t           (Wstat: 6400 Tests: 9 Failed: 1)
  Failed test:  8
  Non-zero exit status: 25
  Parse errors: Bad plan.  You planned 14 tests but ran 9.
Files=62, Tests=2531, 172 wallclock secs ( 1.79 usr  0.25 sys + 108.12 cusr  6.63 csys = 116.79 CPU)
Result: FAIL
Failed 2/62 test programs. 2/2531 subtests failed.
Makefile:2114: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

**Comment by GregDuhamel** [comment]
You should install Padre from this repository, not from CPAN.


PS: i know i don’t answer your question at all ! My bad.


Regards,

Gregory.



De : nbdsp
Envoyé : ‎mardi‎ ‎31‎ ‎mars‎ ‎2015 ‎21‎:‎43
À : PadreIDE/Padre





When installing from CPAN, two tests failed:

------ 1-st : --------
t/01_compile.t ............. 36/37 

Failed test 'no warnings'

at /home/al/perl5/lib/perl5/Test/NoWarnings.pm line 45.

There were 1 warning(s)

Previous test 26 'use Padre::Role::Task;'

Possible precedence issue with control flow operator at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre/Document/Perl/QuickFix/StrictWarnings.pm line 71.

at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre/Document/Perl/QuickFix/StrictWarnings.pm line 71.

require Padre/Document/Perl/QuickFix/StrictWarnings.pm called at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre.pm line 87

eval {...} called at /home/al/.cpan/build/Padre-1.00-CHZPIR/blib/lib/Padre.pm line 87

Padre::import("Padre", ":everything") called at t/01_compile.t line 53

Looks like you failed 1 test of 37.

-------- 2-nd: -----------

t/50_browser.t ............. 1/14 

Failed test 'undef isa 'Padre::Browser::Document''

at t/50_browser.t line 47.

undef isn't defined

Can't call method "mimetype" on an undefined value at t/50_browser.t line 48.

Looks like you planned 14 tests but ran 9.

Looks like you failed 1 test of 9 run.

Looks like your test exited with 25 just after 9.

t/50_browser.t ............. Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 6/14 subtests 

Test Summary Report

t/01_compile.t (Wstat: 256 Tests: 37 Failed: 1)
Failed test: 37
Non-zero exit status: 1
t/50_browser.t (Wstat: 6400 Tests: 9 Failed: 1)
Failed test: 8
Non-zero exit status: 25
Parse errors: Bad plan. You planned 14 tests but ran 9.
Files=62, Tests=2531, 172 wallclock secs ( 1.79 usr 0.25 sys + 108.12 cusr 6.63 csys = 116.79 CPU)
Result: FAIL
Failed 2/62 test programs. 2/2531 subtests failed.
Makefile:2114: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255

**Comment by nbdsp** [comment]
From the git it installed OK. Thanks for the advice!
