### ISSUE TITLE
Debugger cannot invoke Perl and crashes

### ISSUE THREAD

**Issue by Yeti52** [PadreIDE/Padre#16]
I have this issue documented in Word and will try to attach my documentation.

**Comment by Yeti52** [comment]
Contact me via e-mail and I can send the document that way.

**Comment by azawawi** [comment]
Any update on this one?

**Comment by Yeti52** [comment]
Nope.  Once the Debugger dies it takes the Padre environment down and has to be restarted.  And uninstalling, cleaning the file system (of what I know) and Windows Registry and then reinstalling doesn't make it go away.  I had to install on another system to keep going on what I was working on.  I haven't been using Padre in a while though.  Just thought you guys needed to know about this problem.

**Comment by Yeti52** [comment]
Ahmad,

As a follow up, I don’t remember if I put in what I was doing when the Debugger got fragged.  I was debugging and changed code, saved and started debugging again whilst in debugging mode.  I believe that is the original cause of the problem.

Thanks,

- Dave
Anonymous: “Writing wrongs, one word at a time.”
