### ISSUE TITLE
Use padre.perlide.org as website

### ISSUE THREAD

**Issue by chrstphrchvz** [PadreIDE/Padre#36]
Near the top of the [GitHub repo (Code tab)](https://github.com/PadreIDE/Padre), next to the description is a link that currently just points to https://github.com/.

The purpose of this link is to point to the project's homepage, which in this case would be http://padre.perlide.org/.

An owner or member of the repo should be able to update this by clicking the "Edit" button that appears for them to the right of the description (see https://stackoverflow.com/a/21649064/4896937 for an illustration).

**Comment by szabgab** [comment]
Done. thanks for the reminder
