### ISSUE TITLE
Error loading pod for class 'Padre::Plugin::My': Can't call method "mimetype" on an undefined value at C:/Perl/perl/site/lib/Padre/Browser.pm line 305.

### ISSUE THREAD

**Issue by hvoid** [PadreIDE/Padre#9]
Hi.
I have installed Strawberry for Windows and compiled PADRE 1.0.
If I go in Tools>Plugin Manager I get the message for whichever plugin I enable.
It's not a fatal error, but I don't know how to correct it.
Any hint?
![screenshot_1](https://cloud.githubusercontent.com/assets/2746321/5691756/bd9f2514-98d6-11e4-87b9-e995f69556b5.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/2746321/5691758/c1326786-98d6-11e4-8fc0-e63a1284d0c4.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/2746321/5691764/ff7a847e-98d6-11e4-8c98-ca468da45161.jpg)

**Comment by GregDuhamel** [comment]
You may have a look at the following link :

http://mail.perlide.org/pipermail/padre-dev/2014-March/003592.html

Regards,
Gregory.

-- 
Gregory Duhamel

**Comment by hvoid** [comment]
Hi Gregory,
I read what you suggested but I didn't find an answer to my specific issue.
It tells to comment a line that in my browser.cm is not present.
Here a pic of my installed perl.
![screenshot_1](https://cloud.githubusercontent.com/assets/2746321/5692541/2cd9a2d8-98fa-11e4-9d42-402eea78b75b.jpg)
Sorry I can't debug briefly the browser.cm file, I just installed perl and padre to start studying perl.
I am absolutely noob at the language :-)
Is there a way to attach the browser.cm file so that anyone good in perl can take a look at it and tell what should be the solution?
Thanks and regards.

**Comment by GregDuhamel** [comment]
Hello,

I think this patch has been merged with the Master branch (correct me if I'm wrong please).

So, you should clone the Padre repo and launch in it :

# perl Makefile.PL
# dmake 
# dmake test
# dmake install UNINST=1
Regards,
Gregory.

**Comment by hvoid** [comment]
Hello,
I don't know if I am eligible to correct you :-p I can only tell you I got the Padre repo and all the dependencies from CPAN less than a week ago, so I think I used last repo about time.
Do you think, in this case, I have to try to do what you wrote here above?
Had you the time to give a sight to the file I shared in my previous answer?

Thanks and Kind Regards,

**Comment by hvoid** [comment]
Greg perfect!!! :-)
CPAN repo is not fixed.
I cloned from GitHub and it's working.
Great work :-))

Have a nice day.
Thanks,
